# **Feature Selection using Genetic Algorithm (GA)**



A **Genetic Algorithm (GA)** is a type of optimization algorithm inspired by the process of natural selection and genetics. It is commonly used to find optimal or near-optimal solutions to optimization and search problems. The algorithm works by iteratively evolving a population of candidate solutions over multiple generations, mimicking the process of natural selection, crossover, and mutation.

Here's how a genetic algorithm typically works:

**Initialization:** The algorithm starts by generating an initial population of candidate solutions randomly or using some heuristic method.

**Evaluation:** Each candidate solution in the population is evaluated using a fitness function, which quantifies how good the solution is with respect to the optimization problem being solved.

**Selection:** Candidate solutions are selected to form the next generation based on their fitness scores. Solutions with higher fitness scores are more likely to be selected, simulating the concept of "survival of the fittest."

**Crossover:** Selected solutions (parents) are combined to create new solutions (offspring) through crossover or recombination operations. This mimics genetic recombination in biological reproduction.

**Mutation:** Random changes are introduced to some of the offspring solutions to maintain genetic diversity within the population.

**Replacement:** The new generation replaces the old generation, and the process repeats from step 2 for a fixed number of generations or until a termination criterion is met (e.g., convergence).

By iteratively applying selection, crossover, and mutation, genetic algorithms explore the search space efficiently, often finding high-quality solutions even in complex and multimodal optimization problems. They are widely used in various fields, including engineering, finance, biology, and machine learning, where traditional optimization methods may struggle to find satisfactory solutions.

In this notebook, we utilized a loan dataset, accessible at https://www.kaggle.com/datasets/mirzahasnine/loan-data-set, to identify significant features within the data using a Genetic Algorithm (GA).

In [ ]:
import pandas as pd

# Define the file path
file_path = '/content/sample_data/loan_train.csv'

# Load the CSV file into a DataFrame
df = pd.read_csv(file_path)
df

Gender Married Dependents     Education Self_Employed  Applicant_Income  \
0      Male      No          0      Graduate            No            584900   
1      Male     Yes          1      Graduate            No            458300   
2      Male     Yes          0      Graduate           Yes            300000   
3      Male     Yes          0  Not Graduate            No            258300   
4      Male      No          0      Graduate            No            600000   
..      ...     ...        ...           ...           ...               ...   
609  Female      No          0      Graduate            No            290000   
610    Male     Yes         3+      Graduate            No            410600   
611    Male     Yes          1      Graduate            No            807200   
612    Male     Yes          2      Graduate            No            758300   
613  Female      No          0      Graduate           Yes            458300   

     Coapplicant_Income  Loan_Amount   Term  Credit_History       Area Status  
0                   0.0     15000000  360.0             1.0      Urban      Y  
1              150800.0     12800000  360.0             1.0      Rural      N  
2                   0.0      6600000  360.0             1.0      Urban      Y  
3              235800.0     12000000  360.0             1.0      Urban      Y  
4                   0.0     14100000  360.0             1.0      Urban      Y  
..                  ...          ...    ...             ...        ...    ...  
609                 0.0      7100000  360.0             1.0      Rural      Y  
610                 0.0      4000000  180.0             1.0      Rural      Y  
611             24000.0     25300000  360.0             1.0      Urban      Y  
612                 0.0     18700000  360.0             1.0      Urban      Y  
613                 0.0     13300000  360.0             0.0  Semiurban      N  

[614 rows x 12 columns]

In [ ]:
# Drop rows with null values
df_cleaned = df.dropna()

# Check for null values
null_values = df_cleaned.isnull().sum()

# Display the null value counts
print("Null value counts:")
print(null_values)



Null value counts:
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
Applicant_Income      0
Coapplicant_Income    0
Loan_Amount           0
Term                  0
Credit_History        0
Area                  0
Status                0
dtype: int64


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Apply label encoding to categorical columns
categorical_columns = ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Area','Status']
for column in categorical_columns:
    df_cleaned[column] = label_encoder.fit_transform(df_cleaned[column])

# Display the DataFrame after label encoding
print(df_cleaned.head())



   Gender  Married  Dependents  Education  Self_Employed  Applicant_Income  \
0       1        0           0          0              0            584900   
1       1        1           1          0              0            458300   
2       1        1           0          0              1            300000   
3       1        1           0          1              0            258300   
4       1        0           0          0              0            600000   

   Coapplicant_Income  Loan_Amount   Term  Credit_History  Area  Status  
0                 0.0     15000000  360.0             1.0     2       1  
1            150800.0     12800000  360.0             1.0     0       0  
2                 0.0      6600000  360.0             1.0     2       1  
3            235800.0     12000000  360.0             1.0     2       1  
4                 0.0     14100000  360.0             1.0     2       1  


<ipython-input-3-b1d3e02a4891>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = label_encoder.fit_transform(df_cleaned[column])
<ipython-input-3-b1d3e02a4891>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = label_encoder.fit_transform(df_cleaned[column])
<ipython-input-3-b1d3e02a4891>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the document

Genetic algorithms (GAs) are population-based optimization algorithms inspired by the process of natural selection and evolution. They can be effectively used for feature selection in machine learning tasks. Here's how a genetic algorithm typically works for feature selection:

1. **Initialization**:
   - Start by generating an initial population of potential feature subsets. Each individual in the population represents a candidate solution, i.e., a subset of features.
   - The population size can be determined based on the problem's complexity and computational resources.

2. **Evaluation (Fitness Function)**:
   - Evaluate the fitness of each individual (feature subset) in the population using a fitness function.
   - The fitness function measures how well each feature subset performs on the given machine learning task. This can be based on performance metrics such as accuracy, precision, recall, or any other relevant metric.

3. **Selection**:
   - Select individuals from the current population to serve as parents for the next generation.
   - Individuals with higher fitness scores are more likely to be selected, but the selection process may also include some degree of randomness to maintain diversity in the population.

4. **Crossover (Recombination)**:
   - Perform crossover (also known as recombination) to create offspring individuals by combining features from selected parent individuals.
   - This process involves exchanging genetic information (features) between pairs of parent individuals to generate new feature subsets.

5. **Mutation**:
   - Introduce random changes (mutations) to the offspring individuals to maintain genetic diversity.
   - Mutation may involve adding or removing features from the feature subsets with a certain probability.

6. **Replacement**:
   - Replace the old population with the new population of offspring individuals.
   - Some selection criteria may be applied to determine which individuals are retained in the new population, such as elitism (keeping the best individuals from the previous generation).

7. **Termination**:
   - Repeat the selection, crossover, mutation, and replacement steps for multiple generations or until a termination condition is met.
   - Termination conditions may include reaching a maximum number of generations, achieving a satisfactory level of performance, or convergence of the population.

8. **Result**:
   - The final result of the genetic algorithm is the feature subset with the highest fitness score obtained after the termination condition is met.
   - This feature subset is then used for training a machine learning model on the selected features.

By iteratively evolving populations of feature subsets through selection, crossover, and mutation operations, genetic algorithms can efficiently search through the space of possible feature combinations to identify subsets that lead to improved performance on the given machine learning task.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Function to create initial population
def create_population(pop_size, num_features):
    return np.random.randint(2, size=(pop_size, num_features))

# Function to calculate fitness
def fitness(population, X_train, X_test, y_train, y_test):
    fitness_scores = []
    for chromosome in population:
        selected_features = [i for i in range(len(chromosome)) if chromosome[i] == 1]
        if len(selected_features) == 0:
            fitness_scores.append(0)
            continue
        clf = RandomForestClassifier()  # You can replace this classifier with any other
        clf.fit(X_train[:, selected_features], y_train)
        fitness_scores.append(clf.score(X_test[:, selected_features], y_test))
    return np.array(fitness_scores)

# Function to perform selection
def selection(population, fitness_scores):
    selected_indices = np.random.choice(len(population), size=len(population), replace=True, p=fitness_scores/fitness_scores.sum())
    return population[selected_indices]

# Function to perform crossover
def crossover(parent1, parent2):
    crossover_point = np.random.randint(len(parent1))
    child1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    child2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
    return child1, child2

# Function to perform mutation
def mutate(chromosome, mutation_rate):
    for i in range(len(chromosome)):
        if np.random.random() < mutation_rate:
            chromosome[i] = 1 - chromosome[i]
    return chromosome

# Genetic Algorithm
def genetic_algorithm(X_train, X_test, y_train, y_test, num_generations, pop_size, mutation_rate, feature_names, num_runs):
    best_solution_all_runs = []
    best_fitness_all_runs = []

    for run in range(num_runs):
        num_features = X_train.shape[1]
        population = create_population(pop_size, num_features)
        best_fitness = 0
        best_solution = None

        for gen in range(num_generations):
            fitness_scores = fitness(population, X_train, X_test, y_train, y_test)
            population = selection(population, fitness_scores)

            new_population = []

            for i in range(0, pop_size, 2):
                parent1, parent2 = population[i], population[i+1]
                child1, child2 = crossover(parent1, parent2)
                child1 = mutate(child1, mutation_rate)
                child2 = mutate(child2, mutation_rate)
                new_population.extend([child1, child2])

            population = np.array(new_population)

            current_best_fitness = fitness(population, X_train, X_test, y_train, y_test).max()
            if current_best_fitness > best_fitness:
                best_fitness = current_best_fitness
                best_solution = population[np.argmax(fitness(population, X_train, X_test, y_train, y_test))]

            # Print best fitness, solution, and chromosome for each generation
            print(f"Run {run+1}, Generation {gen+1}: Best fitness - {current_best_fitness}")
            print(f"Run {run+1}, Generation {gen+1}: Best solution - {best_solution}")
            selected_feature_names = [feature_names[i] for i in range(len(best_solution)) if best_solution[i] == 1]
            print(f"Run {run+1}, Generation {gen+1}: Best solution features - {selected_feature_names}")

        best_solution_all_runs.append(best_solution)
        best_fitness_all_runs.append(best_fitness)

    return best_solution_all_runs, best_fitness_all_runs


# Extract features and target
X = df_cleaned.drop(columns=['Status'])  # Extract features by dropping the target column
y = df_cleaned['Status']  # Extract the target column
feature_names = X.columns

# Convert X and y to numpy arrays
X = X.values
y = y.values

# Split dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform runs of the genetic algorithm
num_generations = 10
pop_size = 50
mutation_rate = 0.1
num_runs = 5

best_solutions, best_fitnesses = genetic_algorithm(X_train, X_test, y_train, y_test, num_generations, pop_size, mutation_rate, feature_names, num_runs)

for run in range(num_runs):
    print(f"Run {run+1}:")
    print("Best solution:")
    best_solution = best_solutions[run]
    best_fitness = best_fitnesses[run]
    for idx, (feature_idx, feature_value) in enumerate(zip(range(len(best_solution)), best_solution)):
        feature_name = feature_names[feature_idx]
        print(f"Index: {idx}, Feature: {feature_name}, Solution: {feature_value}")
    print(f"Best fitness: {best_fitness}")
    print("\n")


Run 1, Generation 1: Best fitness - 0.87
Run 1, Generation 1: Best solution - [0 1 0 1 1 1 1 1 1 1 0]
Run 1, Generation 1: Best solution features - ['Married', 'Education', 'Self_Employed', 'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Term', 'Credit_History']
Run 1, Generation 2: Best fitness - 0.86
Run 1, Generation 2: Best solution - [0 1 0 1 1 1 1 1 1 1 0]
Run 1, Generation 2: Best solution features - ['Married', 'Education', 'Self_Employed', 'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Term', 'Credit_History']
Run 1, Generation 3: Best fitness - 0.86
Run 1, Generation 3: Best solution - [0 1 0 1 1 1 1 1 1 1 0]
Run 1, Generation 3: Best solution features - ['Married', 'Education', 'Self_Employed', 'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Term', 'Credit_History']
Run 1, Generation 4: Best fitness - 0.85
Run 1, Generation 4: Best solution - [0 1 0 1 1 1 1 1 1 1 0]
Run 1, Generation 4: Best solution features - ['Married', 'Education', 'Self_Em

In [ ]:
best_fitnesses

[0.87, 0.87, 0.88, 0.87, 0.87]

In [ ]:
best_solutions

[array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0]),
 array([0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0]),
 array([1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1]),
 array([0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1])]

In [ ]:
from collections import Counter

# Find the index of the highest fitness score
best_indices = np.where(best_fitnesses == np.max(best_fitnesses))[0]

# Retrieve the corresponding best solutions
best_solutions_selected = [best_solutions[i] for i in best_indices]

# Count the occurrences of 1s and 0s at each index position
counters = [Counter(solution) for solution in zip(*best_solutions_selected)]

# Determine the majority value at each index position
majority_values = [counter.most_common(1)[0][0] for counter in counters]

# Create the best solution based on the majority values
best_solution_majority = np.array([majority_values[i] for i in range(len(majority_values))])

# Print the best solution based on the majority values
print("Best solution based on majority values:")
for idx, (feature_idx, feature_value) in enumerate(zip(range(len(best_solution_majority)), best_solution_majority)):
    feature_name = feature_names[feature_idx]
    print(f"Index: {idx}, Feature: {feature_name}, Solution: {feature_value}")

Best solution based on majority values:
Index: 0, Feature: Gender, Solution: 0
Index: 1, Feature: Married, Solution: 0
Index: 2, Feature: Dependents, Solution: 0
Index: 3, Feature: Education, Solution: 0
Index: 4, Feature: Self_Employed, Solution: 1
Index: 5, Feature: Applicant_Income, Solution: 1
Index: 6, Feature: Coapplicant_Income, Solution: 0
Index: 7, Feature: Loan_Amount, Solution: 0
Index: 8, Feature: Term, Solution: 1
Index: 9, Feature: Credit_History, Solution: 1
Index: 10, Feature: Area, Solution: 0
